language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - cp src/settings.py.example src/settings.py
  - pip install pycodestyle
script:
  - nosetests -v --nocapture
  - pycodestyle --exclude=migrations --ignore=E501,E251,E265,E402,E722 ./ 
notifications:
  email: false
